name: "Backend CI: Spring boot & Java 25"

on:  
    push:
        branches:
            - main


jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: "Configurar JDK 21"
              uses: action/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: 'gradle'

            - name: "Gradle Build"
              run: ./gradlew build